volumes:
  postgres_data:
  # This named volume binds your WSL folder to Docker so Kestra can see your code
  estate_code:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: .

services:
  # The Core Database
  pgdatabase:
    image: postgres:15
    container_name: pgdatabase
    environment:
      POSTGRES_DB: estate_db
      POSTGRES_USER: estate_user
      POSTGRES_PASSWORD: estate_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Database UI for easy querying
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8085:80"
    depends_on:
      - pgdatabase

  # The Orchestrator
  kestra:
    image: kestra/kestra:latest-full
    container_name: kestra
    user: "root"
    command: server local
    environment:
      KESTRA_CONFIGURATION: |
        kestra:
          repository:
            type: postgres
            postgres:
              url: jdbc:postgresql://pgdatabase:5432/estate_db
              username: estate_user
              password: estate_password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    depends_on:
      - pgdatabase